// Mocks generated by Mockito 5.4.6 from annotations
// in simple_note/test/repositories/note_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:simple_note/models/note/note_model.dart' as _i2;
import 'package:simple_note/models/note/update_note_model.dart' as _i5;
import 'package:simple_note/services/note_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNoteModel_0 extends _i1.SmartFake implements _i2.NoteModel {
  _FakeNoteModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NoteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteService extends _i1.Mock implements _i3.NoteService {
  MockNoteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.NoteModel>> getNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getNotes, []),
            returnValue: _i4.Future<List<_i2.NoteModel>>.value(
              <_i2.NoteModel>[],
            ),
          )
          as _i4.Future<List<_i2.NoteModel>>);

  @override
  _i4.Future<_i2.NoteModel> addNote({
    required String? title,
    required String? content,
    String? subjectName,
    List<String>? tagNames,
    bool? isPublic = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addNote, [], {
              #title: title,
              #content: content,
              #subjectName: subjectName,
              #tagNames: tagNames,
              #isPublic: isPublic,
            }),
            returnValue: _i4.Future<_i2.NoteModel>.value(
              _FakeNoteModel_0(
                this,
                Invocation.method(#addNote, [], {
                  #title: title,
                  #content: content,
                  #subjectName: subjectName,
                  #tagNames: tagNames,
                  #isPublic: isPublic,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.NoteModel>);

  @override
  _i4.Future<_i2.NoteModel> editNote({
    required int? id,
    required _i5.UpdateNoteRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editNote, [], {#id: id, #request: request}),
            returnValue: _i4.Future<_i2.NoteModel>.value(
              _FakeNoteModel_0(
                this,
                Invocation.method(#editNote, [], {#id: id, #request: request}),
              ),
            ),
          )
          as _i4.Future<_i2.NoteModel>);
}
