// Mocks generated by Mockito 5.4.6 from annotations
// in simple_note/test/viewmodels/comment_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:simple_note/models/comment/comment_model.dart' as _i4;
import 'package:simple_note/repositories/comment_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CommentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentRepository extends _i1.Mock implements _i2.CommentRepository {
  MockCommentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CommentModel>> getComments(int? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [noteId]),
            returnValue: _i3.Future<List<_i4.CommentModel>>.value(
              <_i4.CommentModel>[],
            ),
          )
          as _i3.Future<List<_i4.CommentModel>>);

  @override
  _i3.Future<void> addComment({
    required int? noteId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [], {
              #noteId: noteId,
              #content: content,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteComment(int? commentId, int? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [commentId, noteId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
