// Mocks generated by Mockito 5.4.6 from annotations
// in simple_note/test/viewmodels/note_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:image_picker/image_picker.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:simple_note/models/note/note_model.dart' as _i4;
import 'package:simple_note/models/note/update_note_model.dart' as _i5;
import 'package:simple_note/repositories/note_repository.dart' as _i2;
import 'package:simple_note/services/text_recognition_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteRepository extends _i1.Mock implements _i2.NoteRepository {
  MockNoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.NoteModel>> getNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getNotes, []),
            returnValue: _i3.Future<List<_i4.NoteModel>>.value(
              <_i4.NoteModel>[],
            ),
          )
          as _i3.Future<List<_i4.NoteModel>>);

  @override
  _i3.Future<void> addNote({
    required String? title,
    required String? content,
    required bool? isPublic,
    String? subject,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addNote, [], {
              #title: title,
              #content: content,
              #isPublic: isPublic,
              #subject: subject,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> editNote({
    required int? id,
    required _i5.UpdateNoteRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editNote, [], {#id: id, #request: request}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [TextRecognitionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextRecognitionService extends _i1.Mock
    implements _i6.TextRecognitionService {
  MockTextRecognitionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> recognizeTextFromImage({
    required _i7.ImageSource? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recognizeTextFromImage, [], {#source: source}),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> scanFromCamera() =>
      (super.noSuchMethod(
            Invocation.method(#scanFromCamera, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
